### ISSUE TITLE
Is this possible...

### ISSUE THREAD

**Issue by SilvorMike** [JABirchall/NimdaDiscord#17]
Hi @JABirchall - please can you confirm if it is possible for the bot to

@Mention someone specific in a standard reply (i.e. I want to mention two admins if a reply is negative).

Send a DM to the author of the message and send a copy to two admins...i.e. can I specify which user to message using
```
return $message->author->createDM()->then(function (DMChannel $channel) use ($expire, $numDays, $author) {
	
        	return $channel->send("Hey $author! Your newsletter subscription will expire $expire. ".$numDays."");
    })->otherwise(function($error) {
       var_dump($error);
    });

```

**Comment by JABirchall** [comment]
Mentions are a special markup, you mention someone using their User ID (. The mention format is <@USER_ID> (i.e. `<@{$author->id}>`.

**Comment by SilvorMike** [comment]
Thanks again @JABirchall - I really appreciate your help.

I am also wondering if it's possible to mention a channel and it be clickable?

I have an Embed like
->addField($message->author->username." ran a command", "You need to visit the #signup channel for more information")

I've tried <#signup> and it didn't work.

Not sure how to implement.

Thanks for all your help.

**Comment by JABirchallHR** [comment]
Its a simular thing for Channels, instead of the name, you put in the id.
<#$channel->id>

**Comment by SilvorMike** [comment]
Thanks @JABirchallHR I had tried that and it was just echoing

<#>

It looks like
->addField($message->author->username." ran a command", "You need to visit the <#".$channel->id."> signup channel for more information")

I also tried
->addField($message->author->username." ran a command", "You need to visit the <#".$channel->{'123456789'}."> signup channel for more information")
