### ISSUE TITLE
Embed Messages

### ISSUE THREAD

**Issue by SilvorMike** [JABirchall/NimdaDiscord#18]
Hello @JABirchall 

Thank you again for such a wonderful bot.

Please can you assist whether it is possible to reply with embed messages as per the system here: https://discordjs.guide/popular-topics/embeds.html#using-the-richembedmessageembed-constructor

Thank you so much

**Comment by JABirchall** [comment]
Yea you can send embeded messages by using the embeded message model class

`$embed = new MessageEmbed();`

Docs for that class is: https://carchive.github.io/Yasmin/master/CharlotteDunois/Yasmin/Models/MessageEmbed.html

**Comment by SilvorMike** [comment]
Amazing thank you!
