### ISSUE TITLE
WSConnection::reconnect() Error

### ISSUE THREAD

**Issue by SilvorMike** [JABirchall/NimdaDiscord#20]
Hi @JABirchall 
I keep getting this error in terminal. I've never had it before. I've recently enabled welcome message embed on the welcome event.

Could it be that?

Error:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CharlotteDunois\Yasmin\WebSocket\WSConnection::reconnect() must be of the type bool, null given, called in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/Handlers/Reconnect.php on line 24 and defined in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php:296
> Stack trace:
> #0 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/Handlers/Reconnect.php(24): CharlotteDunois\Yasmin\WebSocket\WSConnection->reconnect()
> #1 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSHandler.php(81): CharlotteDunois\Yasmin\WebSocket\Handlers\Reconnect->handle()
> #2 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php(640): CharlotteDunois\Yasmin\WebSocket\WSHandler->handle()
> #3 /home/Silvor/public_html/composer/ in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php on line 296
> 
> Fatal error: Uncaught TypeError: Argument 1 passed to CharlotteDunois\Yasmin\WebSocket\WSConnection::reconnect() must be of the type bool, null given, called in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/Handlers/Reconnect.php on line 24 and defined in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php:296
> Stack trace:
> #0 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/Handlers/Reconnect.php(24): CharlotteDunois\Yasmin\WebSocket\WSConnection->reconnect()
> #1 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSHandler.php(81): CharlotteDunois\Yasmin\WebSocket\Handlers\Reconnect->handle()
> #2 /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php(640): CharlotteDunois\Yasmin\WebSocket\WSHandler->handle()
> #3 /home/Silvor/public_html/composer/ in /home/Silvor/public_html/composer/NimdaDiscord/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php on line 296
>

**Comment by JABirchallHR** [comment]
There has been a change on discords end. This is causing these errors.

**Comment by JABirchall** [comment]
Unfurtually @CharlotteDunois has deleted the yasmin package. So i am unable to push a fix to it.
This effectivly kills NimdaDiscord untill a new replacement package can take its place

**Comment by SilvorMike** [comment]
This is awful news. We use NimdaDiscord heavily, it's amazing! 
Can @CharlotteDunois not provide you with a full fork of the source so you can take over if you wanted? Nimda can't die!

**Comment by SilvorMike** [comment]
@JABirchallHR Do you think you'll be able to carry on Nimda - it would be an amazing shame to see it go? I use a lot of PHP functions as part of my bot for MySQL Input etc, it's the best there is! 
Is there a way I can make a fix localhost temporarily ?

**Comment by JABirchall** [comment]
At this moment, Its unclear if or not i can carry on with Nimda. If i can find a package that would be able replace the package then yes, anything else, may require a rewrite of the bot.

**Comment by JABirchall** [comment]
This issue has been resolved in release [0.5.0](https://github.com/JABirchall/NimdaDiscord/releases/tag/0.5.0)
